import Head from "next/head";
import axios from "axios";
import Slider from "../components/Slider";
import styles from "../styles/Home.module.css";
import PizzaList from "../components/PizzaList";
import { useState } from "react";
import { Add } from "../components/Add";

export default function Home({ pizzaList, admin }) {
  const [close, setClose] = useState(true);

  return (
    <div className={styles.container}>
      <Head>
        <title>Pizza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider />
      {admin && <span>hello</span>}
      <PizzaList pizzaList={pizzaList} />
      {!close && <Add/>}
    </div>
  );
}

export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies || "";
  let admin = false;

  if(myCookie.token === process.env.TOKEN){
    admin=true;
  }

  const res = await axios.get("http://localhost:3000/api/products");

  return {
    props: {
      pizzaList: res.data,
      admin
    },
  };
};
